/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.1
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name */
#define CMDLINE_PARSER_PACKAGE PACKAGE
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION VERSION
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * outfile_arg;	/**< @brief Output filename.  */
  char * outfile_orig;	/**< @brief Output filename original value given at command line.  */
  const char *outfile_help; /**< @brief Output filename help description.  */
  int num_samples_arg;	/**< @brief Number of samples.  */
  char * num_samples_orig;	/**< @brief Number of samples original value given at command line.  */
  const char *num_samples_help; /**< @brief Number of samples help description.  */
  int verbose_flag;	/**< @brief verbose (default=off).  */
  const char *verbose_help; /**< @brief verbose help description.  */
  float cutoff_arg;	/**< @brief e-value cutoff.  */
  char * cutoff_orig;	/**< @brief e-value cutoff original value given at command line.  */
  const char *cutoff_help; /**< @brief e-value cutoff help description.  */
  int gtf_flag;	/**< @brief GTF output (default=off).  */
  const char *gtf_help; /**< @brief GTF output help description.  */
  int concise_flag;	/**< @brief Concise output (debugging) (default=off).  */
  const char *concise_help; /**< @brief Concise output (debugging) help description.  */
  int fast_sampling_flag;	/**< @brief Fast sampling (default=off).  */
  const char *fast_sampling_help; /**< @brief Fast sampling help description.  */
  char * debug_file_arg;	/**< @brief Debug file.  */
  char * debug_file_orig;	/**< @brief Debug file original value given at command line.  */
  const char *debug_file_help; /**< @brief Debug file help description.  */
  float print_if_below_arg;	/**< @brief Print alignments below p-value cutoff (debugging).  */
  char * print_if_below_orig;	/**< @brief Print alignments below p-value cutoff (debugging) original value given at command line.  */
  const char *print_if_below_help; /**< @brief Print alignments below p-value cutoff (debugging) help description.  */
  float print_if_above_arg;	/**< @brief Print alignments above p-value cutoff (debugging).  */
  char * print_if_above_orig;	/**< @brief Print alignments above p-value cutoff (debugging) original value given at command line.  */
  const char *print_if_above_help; /**< @brief Print alignments above p-value cutoff (debugging) help description.  */
  int gfx_flag;	/**< @brief Postscript output (default=off).  */
  const char *gfx_help; /**< @brief Postscript output help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int outfile_given ;	/**< @brief Whether outfile was given.  */
  unsigned int num_samples_given ;	/**< @brief Whether num-samples was given.  */
  unsigned int verbose_given ;	/**< @brief Whether verbose was given.  */
  unsigned int cutoff_given ;	/**< @brief Whether cutoff was given.  */
  unsigned int gtf_given ;	/**< @brief Whether gtf was given.  */
  unsigned int concise_given ;	/**< @brief Whether concise was given.  */
  unsigned int fast_sampling_given ;	/**< @brief Whether fast-sampling was given.  */
  unsigned int debug_file_given ;	/**< @brief Whether debug-file was given.  */
  unsigned int print_if_below_given ;	/**< @brief Whether print-if-below was given.  */
  unsigned int print_if_above_given ;	/**< @brief Whether print-if-above was given.  */
  unsigned int gfx_given ;	/**< @brief Whether gfx was given.  */

  char **inputs ; /**< @brief unamed options (options without names) */
  unsigned inputs_num ; /**< @brief unamed options number */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
