/*
  File autogenerated by gengetopt version 2.22.1
  generated with the following command:
  gengetopt -F cmdline --unamed-opts --no-handle-version --no-handle-help --no-handle-error 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                  Print help and exit",
  "  -V, --version               Print version and exit",
  "  -o, --outfile=STRING        Output filename",
  "  -n, --num-samples=INT       Number of samples",
  "  -v, --verbose               verbose  (default=off)",
  "  -e, --cutoff=FLOAT          e-value cutoff",
  "  -g, --gtf                   GTF output  (default=off)",
  "  -t, --concise               Concise output (debugging)  (default=off)",
  "  -f, --fast-sampling         Fast sampling  (default=off)",
  "  -d, --debug-file=STRING     Debug file",
  "  -z, --print-if-below=FLOAT  Print alignments below p-value cutoff (debugging)",
  "  -y, --print-if-above=FLOAT  Print alignments above p-value cutoff (debugging)",
  "  -x, --gfx                   Postscript output  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->outfile_given = 0 ;
  args_info->num_samples_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->cutoff_given = 0 ;
  args_info->gtf_given = 0 ;
  args_info->concise_given = 0 ;
  args_info->fast_sampling_given = 0 ;
  args_info->debug_file_given = 0 ;
  args_info->print_if_below_given = 0 ;
  args_info->print_if_above_given = 0 ;
  args_info->gfx_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->outfile_arg = NULL;
  args_info->outfile_orig = NULL;
  args_info->num_samples_orig = NULL;
  args_info->verbose_flag = 0;
  args_info->cutoff_orig = NULL;
  args_info->gtf_flag = 0;
  args_info->concise_flag = 0;
  args_info->fast_sampling_flag = 0;
  args_info->debug_file_arg = NULL;
  args_info->debug_file_orig = NULL;
  args_info->print_if_below_orig = NULL;
  args_info->print_if_above_orig = NULL;
  args_info->gfx_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->outfile_help = gengetopt_args_info_help[2] ;
  args_info->num_samples_help = gengetopt_args_info_help[3] ;
  args_info->verbose_help = gengetopt_args_info_help[4] ;
  args_info->cutoff_help = gengetopt_args_info_help[5] ;
  args_info->gtf_help = gengetopt_args_info_help[6] ;
  args_info->concise_help = gengetopt_args_info_help[7] ;
  args_info->fast_sampling_help = gengetopt_args_info_help[8] ;
  args_info->debug_file_help = gengetopt_args_info_help[9] ;
  args_info->print_if_below_help = gengetopt_args_info_help[10] ;
  args_info->print_if_above_help = gengetopt_args_info_help[11] ;
  args_info->gfx_help = gengetopt_args_info_help[12] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->outfile_arg));
  free_string_field (&(args_info->outfile_orig));
  free_string_field (&(args_info->num_samples_orig));
  free_string_field (&(args_info->cutoff_orig));
  free_string_field (&(args_info->debug_file_arg));
  free_string_field (&(args_info->debug_file_orig));
  free_string_field (&(args_info->print_if_below_orig));
  free_string_field (&(args_info->print_if_above_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, char *values[])
{
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->outfile_given)
    write_into_file(outfile, "outfile", args_info->outfile_orig, 0);
  if (args_info->num_samples_given)
    write_into_file(outfile, "num-samples", args_info->num_samples_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  if (args_info->cutoff_given)
    write_into_file(outfile, "cutoff", args_info->cutoff_orig, 0);
  if (args_info->gtf_given)
    write_into_file(outfile, "gtf", 0, 0 );
  if (args_info->concise_given)
    write_into_file(outfile, "concise", 0, 0 );
  if (args_info->fast_sampling_given)
    write_into_file(outfile, "fast-sampling", 0, 0 );
  if (args_info->debug_file_given)
    write_into_file(outfile, "debug-file", args_info->debug_file_orig, 0);
  if (args_info->print_if_below_given)
    write_into_file(outfile, "print-if-below", args_info->print_if_below_orig, 0);
  if (args_info->print_if_above_given)
    write_into_file(outfile, "print-if-above", args_info->print_if_above_orig, 0);
  if (args_info->gfx_given)
    write_into_file(outfile, "gfx", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "outfile",	1, NULL, 'o' },
        { "num-samples",	1, NULL, 'n' },
        { "verbose",	0, NULL, 'v' },
        { "cutoff",	1, NULL, 'e' },
        { "gtf",	0, NULL, 'g' },
        { "concise",	0, NULL, 't' },
        { "fast-sampling",	0, NULL, 'f' },
        { "debug-file",	1, NULL, 'd' },
        { "print-if-below",	1, NULL, 'z' },
        { "print-if-above",	1, NULL, 'y' },
        { "gfx",	0, NULL, 'x' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVo:n:ve:gtfd:z:y:x", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->help_given),
              &(local_args_info.help_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "help", 'h',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'V':	/* Print version and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->version_given),
              &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "version", 'V',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'o':	/* Output filename.  */
        
        
          if (update_arg( (void *)&(args_info->outfile_arg), 
               &(args_info->outfile_orig), &(args_info->outfile_given),
              &(local_args_info.outfile_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "outfile", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Number of samples.  */
        
        
          if (update_arg( (void *)&(args_info->num_samples_arg), 
               &(args_info->num_samples_orig), &(args_info->num_samples_given),
              &(local_args_info.num_samples_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "num-samples", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* verbose.  */
        
        
          if (update_arg((void *)&(args_info->verbose_flag), 0, &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* e-value cutoff.  */
        
        
          if (update_arg( (void *)&(args_info->cutoff_arg), 
               &(args_info->cutoff_orig), &(args_info->cutoff_given),
              &(local_args_info.cutoff_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "cutoff", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* GTF output.  */
        
        
          if (update_arg((void *)&(args_info->gtf_flag), 0, &(args_info->gtf_given),
              &(local_args_info.gtf_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "gtf", 'g',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Concise output (debugging).  */
        
        
          if (update_arg((void *)&(args_info->concise_flag), 0, &(args_info->concise_given),
              &(local_args_info.concise_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "concise", 't',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Fast sampling.  */
        
        
          if (update_arg((void *)&(args_info->fast_sampling_flag), 0, &(args_info->fast_sampling_given),
              &(local_args_info.fast_sampling_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "fast-sampling", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Debug file.  */
        
        
          if (update_arg( (void *)&(args_info->debug_file_arg), 
               &(args_info->debug_file_orig), &(args_info->debug_file_given),
              &(local_args_info.debug_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "debug-file", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'z':	/* Print alignments below p-value cutoff (debugging).  */
        
        
          if (update_arg( (void *)&(args_info->print_if_below_arg), 
               &(args_info->print_if_below_orig), &(args_info->print_if_below_given),
              &(local_args_info.print_if_below_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "print-if-below", 'z',
              additional_error))
            goto failure;
        
          break;
        case 'y':	/* Print alignments above p-value cutoff (debugging).  */
        
        
          if (update_arg( (void *)&(args_info->print_if_above_arg), 
               &(args_info->print_if_above_orig), &(args_info->print_if_above_given),
              &(local_args_info.print_if_above_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "print-if-above", 'y',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* Postscript output.  */
        
        
          if (update_arg((void *)&(args_info->gfx_flag), 0, &(args_info->gfx_given),
              &(local_args_info.gfx_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "gfx", 'x',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
