name: Run distcheck

on:
  workflow_dispatch:
    inputs:
      config-flags:
        description: 'Configure flags to prepare the source directory'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      config-flags:
        description: 'Configure flags to prepare the source directory'
        default: ''
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install prerequisites
      run:  |
        sudo apt-get update
        sudo apt-get -y install \
          build-essential \
          autoconf \
          automake \
          gengetopt \
          libtool
    - name: Autotools setup
      run:  |
        autoreconf -i
    - name: Configure
      run: ./configure ${{ inputs.config-flags }}
    - name: distcheck
      run:  make distcheck
