name: Version release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  run-distcheck:
    uses: ./.github/workflows/dist_check.yaml

  create-dist-archives:
    needs: run-distcheck
    uses: ./.github/workflows/dist_archives.yaml
    with:
      zip: true
      artifact-name: 'dist-archives'

  create-release:
    needs: [run-distcheck, create-dist-archives]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download source archives
      uses: actions/download-artifact@v4
      with:
        name: dist-archives
    - name: Make release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "RNAcode-*.tar.gz,RNAcode-*.zip"
        name: "RNAcode ${{ needs.create-dist-archive.outputs.version_number }}"
